server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /console

  datasource:
    platform: h2
    url: jdbc:h2:file:~/test;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true